env:

  rovers:
    - observation_radius: 1000.0
      reward_type: difference
      sensor_type: lidar
      resolution: 90
      position:
        spawn_rule: fixed
        fixed: [25.0, 25.0]

    - observation_radius: 1000.0
      reward_type: difference
      sensor_type: lidar
      resolution: 90
      position:
        spawn_rule: fixed
        fixed: [25.0, 25.0]

    - observation_radius: 1000.0
      reward_type: difference
      sensor_type: lidar
      resolution: 90
      position:
        spawn_rule: fixed
        fixed: [25.0, 25.0]

    - observation_radius: 1000.0
      reward_type: difference
      sensor_type: lidar
      resolution: 90
      position:
        spawn_rule: fixed
        fixed: [25.0, 25.0]
    
    - observation_radius: 1000.0
      reward_type: difference
      sensor_type: lidar
      resolution: 90
      position:
        spawn_rule: fixed
        fixed: [25.0, 25.0]

  pois:
    - type: static
      value: 8.0
      observation_radius: 2.5
      coupling: 2
      position:
        spawn_rule: fixed
        fixed: [15.0, 15.0]

    - type: static
      value: 2.0  
      observation_radius: 2.5
      coupling: 2
      position:
        spawn_rule: fixed
        fixed: [25.0, 10.0]

    - type: static
      value: 4.0
      observation_radius: 2.5
      coupling: 2
      position:
        spawn_rule: fixed
        fixed: [35.0, 15.0]

  img_sensor_size: 25
  team_size: 4
  map_size: [50.0, 50.0]

teaming:
  use_teaming: True
  team_size: 4

ccea: 

  weight_initialization: "kaiming"

  model:
    type: MLP
    hidden_layers: [64, 64]
    rover_max_velocity: 1.0

  population:
    subpopulation_size: 50

  evaluation:
    evaluation_method: HallOfFame

    multi_evaluation:
      num_evaluations: 3
      aggregation_method: average

    hall_of_fame:
      alpha: 0.5
    
    fitness_method: last_step #aggregate/last_step

  selection:
    selection_method: NElitesBinaryTournament
    n_elites: 5
    n_elite_offspring: 0.2

  mutation:
    mean: 0.0
    min_std_deviation: 0.2
    max_std_deviation: 0.6
    lifespan: 0.8 #The higher, the slower the decay, value from 0-1
    independent_probability: 0.5

  num_steps: 30
  num_generations: 4000

processing:
  use_multiprocessing: True
  num_threads: 10

experiment:
  trial_name: multi_mlp_regular
  num_trials: 3
  
data:
  num_gens_between_save: 20
  load_checkpoint_filename: checkpoint.pickle
  load_checkpoint: False
  save_trajectories: True
  save_checkpoint: True
